export const MAJORS = [
  'Computational Media',
  'Computer Engineering',
  'Computer Science',
  'Architecture',
  'Building Construction',
  'Industrial Design',
  'Music Technology',
  'Aerospace Engineering',
  'Biomedical Engineering',
  'Chemical and Biomolecular Engineering',
  'Civil Engineering',
  'Electrical Engineering',
  'Environmental Engineering',
  'Industrial Engineering',
  'Materials Science and Engineering',
  'Mechanical Engineering',
  'Nuclear and Radiological Engineering',
  'Applied Physics',
  'Biochemistry',
  'Biology',
  'Chemistry',
  'Earth and Atmospheric Sciences',
  'Mathematics',
  'Neuroscience',
  'Physics',
  'Psychology',
  'Applied Language and Intercultural Studies',
  'Economics',
  'Economics and International Affairs',
  'Global Economics and Modern Languages',
  'History, Technology, and Society',
  'International Affairs',
  'International Affairs and Modern Languages',
  'Literature, Media, and Communication',
  'Public Policy',
  'Business Administration',
];
